/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

export const storeProducts = [
  {
    id: 1,
    title: "adjustable_step_down",
    img: "/img/adjustable_step_down_module_LM2596.png",
    price: 10,
    company: "Board and Module",
    info: "",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 2,
    title: "4_Channel_5V_10A_Relay",
    img: "img/4_Channel_5V_10A_Relay_Module_with_optocoupler.png",
    price: 12,
    company: "Board and Module",
    info: "Detailed information about the 4 Channel 5V 10A Relay Module.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "12V_2_Amp_Power_Supply",
    img: "img/12V_2_Amp_Power_Supply_Board_220V_AC_to_12V_DC.png",
    price: 8,
    company: "Board and Module",
    info: "Detailed information about the 12V 2 Amp Power Supply Board.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "433_MHz_RF",
    img: "img/433_MHz_RF_transmitter_&_receiver_Module.jpg",
    price: 40,
    company: "Board and Module",
    info: "Detailed information about the 433 MHz RF transmitter & receiver.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "Arduino_Uno_R3",
    img: "img/Arduino_Uno_R3.png",
    price: 300,
    company: "Board and Module",
    info: "Detailed information about the Arduino Uno R3.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "BMP180_Barometric",
    img: "img/BMP180_Barometric_Pressure_Sensor_Module.png",
    price: 50,
    company: "Board and Module",
    info: "Detailed information about the BMP180 Barometric Pressure Sensor.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 7,
    title: "DC_DC_Buck_Converter",
    img: "img/DC_DC_Buck_Converter_Adjustable_Step_Down_Module.jpg",
    price: 30,
    company: "Board and Module",
    info: "Detailed information about the DC-DC Buck Converter Adjustable.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 8,
    title: "Digital_Stereo_Class_D_Audio",
    img: "img/Digital_Stereo_Class_D_Audio_Amplifier_Module.jpg",
    price: 60,
    company: "Board and Module",
    info: "Detailed information about the Digital Stereo Class D Audio Amplifier.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 9,
    title: "HC_SR04_Ultrasonic",
    img: "/img/HC_SR04_Ultrasonic_Distance_Sensor_Module.jpg",
    price: 40,
    company: "Board and Module",
    info: "Detailed information about the HC-SR04 Ultrasonic Distance Sensor.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 10,
    title: "HC_SR501_PIR_Motion",
    img: "/img/HC_SR501_PIR_Motion_Sensor_Detector_Module.jpg",
    price: 40,
    company: "Board and Module",
    info: "Detailed information about the HC-SR501 PIR Motion Sensor Detector.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 11,
    title: "High_Power_2000W_SCR",
    img: "/img/High_Power_2000W_SCR_Voltage_Regulator_Controller.jpg",
    price: 60,
    company: "Board and Module",
    info: "Detailed information about the High Power 2000W SCR Voltage Regulator.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 12,
    title: "Mini_MP3_Player_Module",
    img: "img/XL6009_DC_DC_Adjustable_Step_UP_Boost_Power_Converter_Module.jpg",
    price: 50,
    company: "Board and Module",
    info: "Detailed information about the Mini MP3 Player Module For Arduino.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 13,
    title: "Mini_MP3_Player_Module",
    img: "img/Raspberry_Pi_3_A+_Model_1.4GHz_64_Bit.png",
    price: 1800,
    company: "Board and Module",
    info: "Detailed information about the Mini MP3 Player Module For Arduino.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 14,
    title: "Mini_MP3_Player_Module",
    img: "img/Raspberry_Pi_4_Model_B_2GB_RAM.jpg",
    price: 2500,
    company: "Board and Module",
    info: "Detailed information about the Mini MP3 Player Module For Arduino.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 15,
    title: "Mini_MP3_Player_Module",
    img: "img/Ultrasonic_Sensor_Module_HCSR04_diff_model.jpg",
    price: 50,
    company: "Board and Module",
    info: "Detailed information about the Mini MP3 Player Module For Arduino.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 16,
    title: "Mini_MP3_Player_Module",
    img: "img/Wireless_433Mhz_RF_Module Receiver_Remote_Control_Built_in_Learning_Code_1527_Decoding_4_channel_output.jpg",
    price: 120,
    company: "Board and Module",
    info: "Detailed information about the Mini MP3 Player Module For Arduino.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 17,
    title: "300_PF-0.1UF_Ceramic",
    img: "img/(300)_2PF-0.1UF_ Ceramic_Capacitor_Set_Pack.png",
    price: 175,
    company: "Components",
    info: "300 pieces of ceramic capacitors ranging from 0.1UF to PF values.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 18,
    title: "0.25_watt_1k_ohm_resistor",
    img: "img/0.25_watt_1k_ohm_resistor.png",
    price: 0.50,
    company: "Components",
    info: "0.25 watt 1k ohm resistors.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 19,
    title: "1N4007_Diode",
    img: "img/1N4007_Diode.png",
    price: 1,
    company: "Components",
    info: "1N4007 general purpose diode.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 20,
    title: "2N2222_NPN_Transistor",
    img: "img/2N2222_NPN_Transistor.png",
    price: 3,
    company: "Components",
    info: "2N2222 NPN Bipolar Junction Transistor.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 21,
    title: "3_Pin_JST_Connector_Male",
    img: "img/3_Pin_JST_Connector_Male2.0mm_Pitch_(100).png",
    price: 50,
    company: "Components",
    info: "Pack of 100 3-pin JST connectors with 2.0mm pitch.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 22,
    title: "10uH_Inductor",
    img: "img/10uH_Inductor.png",
    price: 10,
    company: "Components",
    info: "10uH Inductor for electronic circuits.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 23,
    title: "12V_RGB_LED_Strip",
    img: "img/12V_RGB_LED_Strip-_4.5_Meter_SMD.webp",
    price: 130,
    company: "Components",
    info: "4.5 meter SMD RGB LED strip with 12V power supply.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 24,
    title: "16MHz_Crystal_Oscillator",
    img: "img/16MHz_Crystal_Oscillator.png",
    price: 5,
    company: "Components",
    info: "16MHz Crystal Oscillator for frequency stabilization.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 25,
    title: "20mm_LED_Lens_15_",
    img: "img/20mm_LED_Lens_15_Degree_for_High_Power_LED_Light.png",
    price: 70,
    company: "Components",
    info: "20mm LED Lens with 15-degree beam angle for high power LED lights.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 26,
    title: "100uF_25V_Electrolytic",
    img: "img/100uF_25V_Electrolytic_Capacitor.png",
    price: 2,
    company: "Components",
    info: "100uF 25V Electrolytic Capacitor.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 27,
    title: "130pcs_Power_Inductor",
    img: "img/130pcs_Power_Inductor_Assortment_Kit.png",
    price: 116,
    company: "Components",
    info: "130 pieces of various power inductors in an assortment kit.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 28,
    title: "0.1-220uF_Capacitor_Kit",
    img: "img/200_pcs_15_values_0.1-220uF_Capacitor_Kit.png",
    price: 250,
    company: "Components",
    info: "200 pieces of capacitors with 15 different values ranging from 0.1 to 220uF.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 29,
    title: "DHT11 Sensor",
    img: "img/DHT11_Temperature_and_Humidity_Sensor.png",
    price: 75,
    company: "Components",
    info: "DHT11 sensor for measuring temperature and humidity.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 30,
    title: "DIP-8_MICROCHIP",
    img: "img/DIP-8_MICROCHIP_Operational_Amplifier.png",
    price: 115,
    company: "Components",
    info: "Operational amplifier in DIP-8 package.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 31,
    title: "IRLZ44N_MOSFET",
    img: "img/IRLZ44N_MOSFET_Fast_Switching.png",
    price: 30,
    company: "Components",
    info: "IRLZ44N MOSFET for fast switching applications.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 32,
    title: "7805acv_voltage_regulator",
    img: "img/l7805acv_voltage_regulator.png",
    price: 50,
    company: "Components",
    info: "7805ACV voltage regulator for stable 5V output.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 33,
    title: "Lithium_Battery_Level",
    img: "img/Lithium_Battery_Level_Indicator_Module-User_Configurable.png",
    price: 50,
    company: "Components",
    info: "Lithium battery level indicator module that is user-configurable.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 34,
    title: "Micro_130_Small_DC_Motor_3V-6V",
    img: "img/Micro_130_Small_DC_Motor_3V-6V.png",
    price: 10,
    company: "Components",
    info: "Micro 130 small DC motor with 3V-6V operating voltage.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 35,
    title: "NE555_Timer_IC",
    img: "img/NE555_Timer_IC.png",
    price: 20,
    company: "Components",
    info: "NE555 Timer IC for precision timing applications.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 36,
    title: "Ohm_0.25w_Resist_1_Metal",
    img: "img/Ohm_0.25w_Resist_1__Metal_Film_Resistor_Kit.png",
    price: 145,
    company: "Components",
    info: "0.25W Metal Film Resistor Kit with various ohm values.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 37,
    title: "0.5mm_Enamelled_Copper",
    img: "img/0.5mm_Enamelled_Copper_Wire_50g_spool.png",
    price: 100,
    company: "Components",
    info: "0.5mm Enamelled Copper Wire, 50g spool for various electronic projects.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 38,
    title: "3mm_Heat_Shrink_Tubing",
    img: "img/3_mm_Heat_Shrink_Tubing_1_meter.png",
    price: 10,
    company: "Miscellaneous",
    info: "3mm heat shrink tubing, 1 meter long for insulation and protection.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 39,
    title: "1206_SMD_Sample_Book",
    img: "img/1206_SMD_Sample_Book_0Ω_10Ω.png",
    price: 1050,
    company: "Miscellaneous",
    info: "1206 SMD Sample Book with resistors and capacitors ranging from 02Ω to 10Ω.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 40,
    title: "Basic_Electronics_Book",
    img: "img/Basic_Electronics_Book.png",
    price: 500,
    company: "Miscellaneous",
    info: "Basic Electronics Book for beginners.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 41,
    title: "Black_Polyolefin",
    img: "img/Black_Polyolefin_Heat_Shrink_Tube_Sleeve.png",
    price: 30,
    company: "Miscellaneous",
    info: "Black Polyolefin Heat Shrink Tube Sleeve for insulation and protection.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 42,
    title: "Electrical_Alligator_",
    img: "img/Electrical_Alligator_Clips_with_Wires_Test_Leads.png",
    price: 30,
    company: "Miscellaneous",
    info: "Electrical alligator clips with wires for testing and prototyping.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 43,
    title: "Perfboard_50mm_x_70mm",
    img: "img/Perfboard_50_mm_x_70_mm.png",
    price: 10,
    company: "Miscellaneous",
    info: "Perfboard with dimensions 50mm x 70mm for soldering electronic components.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 44,
    title: "Solder_Wire_50gm",
    img: "img/Solder_Wire_50gm.png",
    price: 80,
    company: "Miscellaneous",
    info: "50gm of solder wire for electronic soldering.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 45,
    title: "30W_Soldering_Iron",
    img: "img/30W_Soldering_Iron.png",
    price: 110,
    company: "Tools",
    info: "30W Soldering Iron for electronic soldering projects",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:46,
    title: "40W_Soldering_Iron",
    img: "img/40W_Soldering_Iron.png",
    price: 250,
    company: "Tools",
    info: "40W Soldering Iron for electronic soldering projects",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 47,
    title: "830_Point_Solderless_Breadboard",
    img: "img/830_Point_Solderless_Breadboard.png",
    price: 100,
    company: "Tools",
    info: "830 Point Solderless Breadboard for prototyping electronic circuits",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 48,
    title: "Adjustable_Wire_Stripper",
    img: "img/Adjustable_Wire_Stripper.png",
    price: 150,
    company: "Tools",
    info: "Adjustable Wire Stripper for precise wire stripping",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 49,
    title: "Basic_Handheld_Oscilloscope",
    img: "img/Basic_Handheld_Oscilloscope.png",
    price: 10000,
    company: "Tools",
    info: "Basic Handheld Oscilloscope for measuring electronic signals",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 50,
    title: "Digital_Multimeter",
    img: "img/Digital_Multimeter.png",
    price: 300,
    company: "Tools",
    info: "Digital Multimeter for measuring voltage, current, and resistance",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 51,
    title: "ESD_Safe_Precision_Tweezers",
    img: "img/ESD_Safe_Precision_Tweezers.png",
    price: 50,
    company: "Tools",
    info: "ESD Safe Precision Tweezers for handling electronic components",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 52,
    title: "Variable_DC_Power_Supply_(0-30V_5A)",
    img: "img/Variable_DC_Power_Supply_(0-30V,_5A).png",
    price: 2500,
    company: "Tools",
    info: "Variable DC Power Supply (0-30V, 5A) for providing adjustable power to electronic circuits",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 52,
    title: "12V_1A_AC_DC_Adapter",
    img: "img/12V_1A_AC_DC_Adapter.png",
    price: 100,
    company: "Power",
    info: "12V 1A AC/DC Adapter for powering electronic devices.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 53,
    title: "18650_Battery_Holder",
    img: "img/18650_Battery_Holder.png",
    price: 10,
    company: "Power",
    info: "Holder for 18650 lithium-ion batteries.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 54,
    title: "18650_Lithium_Ion_Battery",
    img: "img/18650_Lithium_Ion_Battery.png",
    price: 100,
    company: "Power",
    info: "18650 lithium-ion battery, 3.7V.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 55,
    title: "Small_Solar_Panel_5V",
    img: "img/Small_Solar_Panel_5V.png",
    price: 150,
    company: "Power",
    info: "Small 5V solar panel for charging small devices.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 56,
    title: "2.54mm_Pitch_Male_Header_40_pin",
    img: "img/2.54mm_Pitch_Male_Header_40_pin.jpg",
    price: 50,
    company: "Connectivity",
    info: "2.54mm pitch male header with 40 pins, ideal for prototyping and connecting circuits.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 57,
    title: "Male_to_Male_Jumper_Wires_10_pack",
    img: "img/Male_to_Male_Jumper_Wires_10_pack.jpg",
    price: 100,
    company: "Connectivity",
    info: "Pack of 10 male-to-male jumper wires, useful for breadboard and prototyping connections.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 58,
    title: "USB_Type_A_to_Micro_USB_Cable_1_meter",
    img: "img/USB_Type_A_to_Micro_USB_Cable_1_meter.jpg",
    price: 150,
    company: "Connectivity",
    info: "1 meter USB Type A to Micro USB cable, suitable for data transfer and charging.",
    inCart: false,
    count: 0,
    total: 0
  }
  
];

export const detailProduct = {
  id: 1,
  title: "Board and Module Pixel - Black",
  img: "img/product-1.png",
  price: 10,
  company: "Board and Module",
  info:
    "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0
};
